### ISSUE TITLE
Game is too hard/bikes move to fast

### ISSUE THREAD

**Issue by danithehackr** [jminjie/typebike#1]
I really like the concept of this game, however, upon playing the web version, I have found that the game can be really difficult to survive in for more than a few seconds.

Perhaps there could be multiple difficulty levels and/or the default could be a bit slower?

Thanks so much for making this!

**Comment by jminjie** [comment]
Glad you enjoyed the concept of the game! I really enjoy playing it at the high speed, it's challenging but to me it's evocative of the high speed old-school Tron game. If you want to compile a local version with slower speed, you can clone the repo and modify the line in the Racer class

https://github.com/jminjie/typebike/blob/master/Assets/Scripts/Racer.cs#L66

**Comment by danithehackr** [comment]
Thank you! I will try this :)
